/**
 * Bundles MapLibre's worker into `src/lib/maplibre-gl-worker.js`.
 *
 * Since v6 MapLibre loads its worker from a separate file, resolved at runtime via
 * `new URL('./maplibre-gl-worker.mjs', import.meta.url)`. Bundlers inline `maplibre-gl.mjs`
 * into a chunk, so that URL no longer points anywhere and the worker fails to start.
 *
 * Shipping a self-contained copy inside our own package lets `BasicMap.svelte` reference it
 * with a plain `new URL(..., import.meta.url)`, which every bundler understands — no
 * Vite-specific import queries, which break Vite's dependency pre-bundling (see issue #90).
 *
 * The bundle is generated from the installed `maplibre-gl`, so it always matches the version
 * the main thread uses. `maplibre-gl` is pinned exactly in package.json to keep it that way.
 */

import { build } from 'esbuild';
import { createRequire } from 'node:module';
import { stat } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { resolve } from 'node:path';

const require = createRequire(import.meta.url);
const root = fileURLToPath(new URL('..', import.meta.url));

const entryPoint = require.resolve('maplibre-gl/dist/maplibre-gl-worker.mjs');
const outfile = resolve(root, 'src/lib/maplibre-gl-worker.js');
const version = require('maplibre-gl/package.json').version as string;

await build({
	entryPoints: [entryPoint],
	outfile,
	bundle: true,
	format: 'esm',
	target: 'esnext',
	minify: true,
	legalComments: 'none',
	// `@ts-nocheck` keeps svelte-check from type-checking half a megabyte of minified output
	banner: {
		js: [`// Generated by scripts/bundle_worker.ts from maplibre-gl ${version}. Do not edit.`, '// @ts-nocheck'].join(
			'\n'
		)
	}
});

const { size } = await stat(outfile);
console.log(`bundled maplibre-gl ${version} worker → ${(size / 1024).toFixed(0)} kB`);
