name: CI

on:
  release:
    types:
      - published

jobs:
  screenshots:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Run screenshots
        run: npm run screenshots

      - name: Upload screenshots to release
        uses: softprops/action-gh-release@v2
        with:
          files: ./screenshots/*.png
          token: ${{ secrets.GITHUB_TOKEN }}
