name: Release

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  screenshots:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install chromium

      - name: Run screenshots
        run: npm run screenshots

      - name: Upload screenshots to release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          TAG=$(gh release view --json "tagName" --jq ".tagName")
          gh release upload "$TAG" ./screenshots/*.png --clobber
